### ISSUE TITLE
Commit ID

### ISSUE THREAD

**Issue by soyboy5125** [RichardDorian/Solar-Tweaks#6]
When Ever I Try To Use It I Get This Error

![Capture](https://user-images.githubusercontent.com/89871893/135912617-b4ad6456-f690-4ed0-b3cb-d0672e50219c.PNG)

**Comment by RichardDorian** [comment]
Hi, this happen because the version of Solar Tweaks is outdated. The new version should be released tomorrow. And if it's not working with the new version consider opening a ticket inside our [Discord server](https://discord.gg/SolarTweaks), you will get better support.
